#!/usr/bin/env bash

source ./.bashlib

usage() {
	echo "$script_dir/dev-env"
	echo ""
	echo "Usage:"
	echo "Overwrite your .dotfiles, config files, utility scripts, and more on this computer with what is in $HOME/projects/setup/"
	echo ""
	echo "Flags:"
	_lib_usage
}
if [[ "$usage" == "true" ]]; then
	usage
	exit 0
fi

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
log "$script_dir"

execute cd $script_dir

log "----------- dev-env -----------"
log "ensure submodules are up to date"
execute git fetch --prune
execute git submodule init
execute git submodule update

log "copy config files to runtime locations"

# if no _basetheme has been applied, make sure one exists
if ! [ -d .config/hypr/theme.conf ]; then
	(./_basetheme) # run in sub-shell so PATH changes don't leak out here

	log "----------- re-enter: dev-env -----------"
fi

copy_dir .config $HOME/.config
copy_dir .local $HOME/.local

copy_file home/.profile $HOME
copy_file home/.bashrc $HOME
copy_file home/.bash_profile $HOME
copy_file home/.bash_aliases $HOME
copy_file home/.bash_logout $HOME
copy_file home/.ready-tmux $HOME
copy_file .bashlib $HOME
copy_file .config/tmux/.tmux.conf $HOME

execute source $HOME/.profile
execute source $HOME/.bashrc
execute source $HOME/.bash_profile
execute source $HOME/.bash_aliases
execute source $HOME/.bash_logout

if [[ ! -d "$HOME/projects/wallpapers" ]]; then
	log "no wallpapers found, applying default wallpapers"
	execute mkdir -p ~/projects/wallpapers
	execute cp ./assets/wallpapers/* ~/projects/wallpapers
fi

execute toggledock # setup config files for hypr config
execute reload # reloads hyprland config
