#!/usr/bin/env bash

sudo pacman -Syu update

if ! command -v git &> /dev/null; then
    yes | sudo pacman -S git
fi

if [ ! -d $HOME/projects ]; then
    mkdir -p $HOME/projects
fi

git clone --recursive git@github.com:michael-weems/setup.git $HOME/projects/setup

pushd $HOME/projects/setup
DEV_ENV=$HOME/projects/setup
./init
./run
popd
