#!/usr/bin/env bash

git submodule init
git submodule update

pushd home/.config/nvim
git checkout master
popd

pushd wallpapers
git checkout master
popd 

# TODO: 
# tmux-sessionizer
# tmux-catppuccin
# tmux-rose-pine
