#!/usr/bin/env bash
source ./.bashlib # TODO: expand this
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

pushd ${SCRIPT_DIR}

os=""
for ((i=0; i<argc; i++)); do
	if   [[ "-os" == "${argv[$i]}" ]]; then
		i=$((i + 1))
		os="${argv[$i]}"
	fi
done

if [[ -z "$os" ]]; then
   os=$(find ./os -maxdepth 1 -type d | fzf)
   os=$(basename $os)
   echo "using os: $os"
fi

pushd ./os/${os}
source ./install-pkgs 
popd

