#!/usr/bin/env bash

source ./.bashlib # TODO: expand this
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [ -z "$XDG_CONFIG_HOME" ]; then
    echo "no xdg config home, defaulting to: ~/.config"
    XDG_CONFIG_HOME=$HOME/.config
fi

pushd ${SCRIPT_DIR}

os=""
for ((i=0; i<argc; i++)); do
	if   [[ "-os" == "${argv[$i]}" ]]; then
		i=$((i + 1))
		os="${argv[$i]}"
	fi
done

if [[ -z "$os" ]]; then
	echo "please provide an os: arch, wsl-ubuntu, windows, fedora"
	exit 1
fi

copy() {
	src="$1"
	dest="$2"
	cp -r "$src" "$dest"
}

fresh_copy() {
	src="$1"
	dest="$2"
	rm -fr "$dest"
	cp -r "$src" "$dest"
}


# TODO: each os has it's own scripts for copying / running? so they can augment what gets copied and all that

if [[ "$os" == "windows" ]]; then

	# dirs
	fresh_copy $SCRIPT_DIR/os/${os}/home/.vim $HOME/.vim
	fresh_copy $SCRIPT_DIR/os/${os}/home/.config $XDG_CONFIG_HOME
	fresh_copy $SCRIPT_DIR/os/${os}/home/.local $HOME/.local
	rm -fr $USERPROFILE/AppData/Local/nvim-data
	fresh_copy $SCRIPT_DIR/os/${os}/home/.config/nvim $USERPROFILE/AppData/Local/nvim

	# files
	fresh_copy $SCRIPT_DIR/os/${os}/home/.vimrc $HOME/.vimrc
	fresh_copy $SCRIPT_DIR/os/${os}/home/.profile $HOME/.profile
	fresh_copy $SCRIPT_DIR/os/${os}/home/.bashrc $HOME/.bashrc
	fresh_copy $SCRIPT_DIR/os/${os}/home/.bash_profile $HOME/.bash_profile
	fresh_copy $SCRIPT_DIR/os/${os}/home/.bash_aliases $HOME/.bash_aliases
	fresh_copy $SCRIPT_DIR/os/${os}/home/.bash_logout $HOME/.bash_logout
else
	# dirs
	fresh_copy $SCRIPT_DIR/os/${os}/home/.vim $HOME/.vim
	fresh_copy $SCRIPT_DIR/os/${os}/home/.config $XDG_CONFIG_HOME
	fresh_copy $SCRIPT_DIR/os/${os}/home/.local $HOME/.local

	# files
	fresh_copy $SCRIPT_DIR/os/${os}/home/.vimrc $HOME/.vimrc
	fresh_copy $SCRIPT_DIR/os/${os}/home/.profile $HOME/.profile
	fresh_copy $SCRIPT_DIR/os/${os}/home/.bashrc $HOME/.bashrc
	fresh_copy $SCRIPT_DIR/os/${os}/home/.bash_profile $HOME/.bash_profile
	fresh_copy $SCRIPT_DIR/os/${os}/home/.bash_aliases $HOME/.bash_aliases
	fresh_copy $SCRIPT_DIR/os/${os}/home/.bash_logout $HOME/.bash_logout
fi

fresh_copy $SCRIPT_DIR/.bashlib $HOME/.bashlib

source $HOME/.profile
source $HOME/.bashrc
source $HOME/.bash_profile
source $HOME/.bash_aliases
source $HOME/.bash_logout
 
popd
