#!/usr/bin/env bash

source ./.bashlib # TODO: expand this
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [ -z "$XDG_CONFIG_HOME" ]; then
    echo "no xdg config home, defaulting to: ~/.config"
    XDG_CONFIG_HOME=$HOME/.config
fi

pushd ${SCRIPT_DIR}

os=""
filter=""
for ((i=0; i<argc; i++)); do
	if   [[ "-os" == "${argv[$i]}" ]]; then
		i=$((i + 1))
		os="${argv[$i]}"
	elif [[ "-g" == "${argv[$i]}" ]] || [[ "-grep" == "${argv[$i]}" ]]; then
		i=$((i + 1))
		filter="${argv[$i]}"
	fi
done

if [[ -z "$os" ]]; then
	echo "please provide an os: arch, wsl-ubuntu, windows, fedora"
	exit 1
fi



echo "run: $filter"

scripts=$(find ./runs -maxdepth 1 -mindepth 1 -executable -type f | sort) # find every executable in the runs dir
for script in $scripts; do
	# does this script not contain this filter
	if echo "$script" | grep -qv "$filter"; then
		log "filtering $script"
		continue
	fi
	./$script
done

log "done: please run the below command"
log ""
log "    cd ~/projects/setup && ./dev-env"
log ""

popd
