#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

filter=""
dry="false"

usage() {
	echo "$script_dir/run"
	echo ""
	echo "Usage:"
	echo "Install applications on the computer based on the scripts under $HOME/projects/setup/runs/"
	echo ""
	echo "Arguments:"
	echo "filter          | run only the installation for the applications that match this input filter"
	echo ""
	echo "Flags:"
	echo "-d, --dry-run   | perform a dry-run of the operations"
	echo "-h, --help      | print usage"
	echo ""
	echo "Examples:"
	echo "./run ghostty   # runs the installation for ghostty"
}

echo "$script_dir -- $filter"

cd $script_dir
scripts=$(find ./runs -maxdepth 1 -mindepth 1 -executable -type f) # find every executable in the runs dir

while [[ $# > 0 ]]; do
	if   [[ "$1" == "-d" ]] || [[ "$1" == "--dry" ]]; then
		dry="true"
	elif [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
		usage
		exit 0
	else
		filter="$1"
	fi
	shift
done

log() {
	if [[ $dry == "true" ]]; then
		echo "[DRY_RUN]: $@"
	else
		echo "$@"
	fi
}
execute() {
	log "execute $@"
	if [[ $dry == "true" ]]; then
		return
	fi
	$@
}

log "run: filter=$filter"

for script in $scripts; do
	# does this script not contain this filter
	if echo "$script" | grep -qv "$filter"; then
		log "filtering $script"
		continue
	fi
	execute ./$script
done

