#!/usr/bin/env bash

to="$HOME/.config/waybar"

from=$(find "$to/themes" -mindepth 1 -maxdepth 1 -type f | grep "$1")
echo "from: $from"
if [[ -z "$from" ]]; then
	from="$to/themes/_fallback.css"
fi

name=$(basename $from)

echo "apply theme: $name"

rm "$to/theme.css"
cp "$from" "$to/theme.css"
