#!/usr/bin/env bash

# make sure yay is available
yes | sudo pacman -S --needed git base-devel
git clone https://aur.archlinux.org/yay.git ~/vendor/yay
cd ~/vendor/yay
makepkg -si 

yay -Y --gendb
yay -Syu --devel
yay -Y --devel --save

# dependencies
yes | sudo pacman -S meson
yes | sudo pacman -S cmake
yes | sudo pacman -S libmpdclient
yes | sudo pacman -S startup-notification

# desktop environment tools
yes | sudo pacman -S uwsm libnewt # enable wayland to interact with systemd better
yes | sudo pacman -S qt5-wayland qt6-wayland # enable qt applications
yes | sudo pacman -S pipewire wireplumber # audio server
# https://wiki.hyprland.org/Hypr-Ecosystem/xdg-desktop-portal-hyprland/
yes | sudo pacman -S xdg-desktop-portal-hyprland # enable file-pickers / screensharing
yes | sudo pacman -S hyprpaper 	# wallpaper
yes | sudo pacman -S hyprpicker # desktop color-picker
yes | sudo pacman -S waybar     # status bar
yes | sudo pacman -S ttf-font-awesome # nerd-font
yes | sudo yay -S wlogout # logout menu
yes | sudo pacman -S yazi fd zoxide imagemagick chafa # terminal-based file-navigator
yes | sudo pacman -S libnotify dunst # notification popups
yes | sudo pacman -S udiskie # enable mounting flashdrives
yes | sudo pacman -S fastfetch # print system info

# desktop apps
yes | sudo pacman -S firefox

# devtools
yes | sudo pacman -S jq               # json query
yes | sudo pacman -S 7zip             # archive util
yes | sudo pacman -S ghostty          # my preferred terminal-emulator
yes | sudo pacman -S ripgrep          # alternative to grep, usually better, sometimes worse
yes | sudo pacman -S fzf              # search utility
yes | sudo pacman -S tmux             # terminal-multiplexer for switching contexts efficiently
yes | sudo pacman -S unzip            # unzip things
yes | sudo pacman -S valgrind         # detect memory leaks in programs
yes | sudo pacman -S xclip            # copy to clipboard (eg. cat file | xclip -selection clipboard)

