#!/usr/bin/env bash

sudo apt install bsdutils         # 
sudo apt install build-essentials # 
sudo apt install doc-base         # 
sudo apt install gcc              # tiling window manager
sudo apt install git              # version control
sudo apt install i3               # tiling window manager
sudo apt install make             # general build script tool
sudo apt install nitrogen         # desktop wallpapers
sudo apt install picom            #
sudo apt install pulseaudio-utils #
sudo apt install pulseaudio       #
sudo apt install ripgrep          # alternative to grep, usually better, sometimes worse
sudo apt install tmux             # terminal-multiplexer for switching contexts efficiently
sudo apt install unzip            # unzip things
sudo apt install valgrind         # detect memory leaks in programs
sudo apt install xclip            # 

sudo snap install zig --classic --beta # zig v0.13.0
