#!/usr/bin/env bash

# build from source instructions: https://ghostty.org/docs/install/build

bin="$HOME/.bin/ghostty"
rm -rf "$bin"
mkdir -p "$bin"

# curl a release from github: https://stackoverflow.com/a/46060099
curl -L "https://github.com/mkasberg/ghostty-ubuntu/releases/download/1.0.1-0-ppa4/ghostty_1.0.1-0.ppa4_amd64_24.04.deb" > "$bin/ghostty.deb" 
sudo dpkg -i "$bin/ghostty.deb"

