#!/usr/bin/env bash

git clone --depth 1 -b v0.10.1 https://github.com/neovim/neovim.git $HOME/projects/neovim
cd $HOME/projects/neovim
git fetch
git checkout v0.10.1

sudo apt install cmake gettext lua5.1 liblua5.1-0-dev
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
