#!/usr/bin/env bash

sudo pacman -S --needed git base-devel
git clone https://aur.archlinux.org/yay.git ~/vendor/yay
cd ~/vendor/yay
makepkg -si 

yay -Y --gendb
yay -Syu --devel
yay -Y --devel --save
