#!/usr/bin/env bash

mkdir -p $HOME/.local/bin
if [ -f $HOME/.local/bin ]; then
	# update
	yt-dlp -U
else
	# new install
	curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o ~/.local/bin/yt-dlp
	chmod a+rx ~/.local/bin/yt-dlp  # Make executable
fi
