#!/usr/bin/env bash

LUA_VERSION="5.1.5"

# Lua v5.4 is used for most packages, so we leave it installed as is
# We're using Lua v5.1 for development, so we'll install it locally and alias it

mkdir -p $HOME/vendor/

pushd $HOME
curl -L -R -O https://www.lua.org/ftp/lua-${LUA_VERSION}.tar.gz
tar zxf lua-${LUA_VERSION}.tar.gz -C $HOME/vendor/lua-${LUA_VERSION}/
rm -fr lua-${LUA_VERSION}.tar.gz

if [ -d $HOME/vendor/lua-${LUA_VERSION} ]; then
	rm -fr $HOME/vendor/lua-${LUA_VERSION}
fi

pushd $HOME/vendor/lua-${LUA_VERSION}
make linux
make local
popd

