#!/usr/bin/env bash

# https://odin-lang.org/docs/install/
yes | sudo apt-get install clang llvm
git clone https://github.com/odin-lang/Odin $HOME/vendor/odin
pushd $HOME/vendor/odin
./build_odin.sh release-native

# stb bindings
pushd vendor/stb/src
make
popd

# https://github.com/DanielGavin/ols?tab=readme-ov-file#neovim
# Odin LSP
git clone git@github.com:DanielGavin/ols.git $HOME/vendor/odin-lsp
pushd $HOME/vendor/odin-lsp

./build.sh
./odinfmt.sh

