#!/usr/bin/env bash

pkill hyprpaper 
pkill waybar 

# hypr
hyprctl reload

# waybar
waybar &

# hyprpaper
pkill hyprpaper 
hyprpaper &

# ensure monitors are correct
pkill kanshi && kanshi &

sleep 0.1 && wallpaper --reapply
