#!/usr/bin/env bash

pkill hyprpaper 
pkill waybar 

# hypr
hyprctl reload

# waybar
waybar &

# hyprpaper
pkill hyprpaper 
hyprpaper &

# ensure monitors are correct
pkill kanshi 
kanshi &

pkill antimicrox
antimicrox --profile $HOME/play.gamecontroller.amgp --hidden &

sleep 0.1 
wallpaper --reapply
