#!/usr/bin/env bash

source $HOME/_lib

to="$HOME/.config/hypr"

from=$(find "$to/themes" -mindepth 1 -maxdepth 1 -type f | grep "$1")
echo "from: $from"
if [[ -z "$from" ]]; then
	from="$to/themes/_fallback.conf"
fi

name=$(basename $from)

echo "apply theme: $name"

copy_file $from $to theme.conf

