#!/usr/bin/env bash

pkill hyprpaper 
pkill waybar 

# hypr
hyprctl reload

# waybar
waybar &

# hyprpaper
pkill hyprpaper 
hyprpaper &

wp="$(cat ~/.config/hypr/wallpaper)"

if [[ ! -z "$wp" ]]; then
	sleep 10 && wallpaper --query "$wp"
fi
