#!/usr/bin/env bash

# NOTE: script variables
dry="false"
dock="true"

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

usage() {
	echo "$script_dir/screen <flags>"
	echo ""
	echo "Usage:"
	echo "-u, --undock    | use the built-in laptop screen"
	echo "-d, --dry-run   | perform a dry-run of the operations"
	echo "-h, --help      | print usage"
	echo ""
	echo "Example:"
	echo "./.local/scripts/screen    # dock the laptop and display via the external monitor"
	echo "./.local/scripts/screen -u # undock the laptop and display via the external monitor"
	echo ""
}

# NOTE: parse inputs
while [[ $# > 0 ]]; do
	if   [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
		usage
		exit 0
	elif [[ "$1" == "-d" ]] || [[ "$1" == "--dry-run" ]]; then
		dry="true"
	elif [[ "$1" == "-u" ]] || [[ "$1" == "--undock" ]]; then
		dock="false"
	fi
	shift
done

# NOTE: utility functions
log() {
	if [[ $dry == "true" ]]; then
		echo "[DRY_RUN]: $@"
	else
		echo "$@"
	fi
}
execute() {
	log "$@"
	if [[ $dry == "true" ]]; then
		return
	fi
	$@
}

# NOTE: Actual script starts here

if [ "$dock" == "true" ]; then
	log "dock the laptop"
	execute xrandr --output HDMI-A-0 --auto
	execute xrandr --output eDP --off
else
	log "undock the laptop"
	execute xrandr --output eDP --auto
	execute xrandr --output HDMI-A-0 --off
fi

exit 0

