#!/usr/bin/env bash

source $HOME/_lib

to="$HOME/.config/hypr"

monitor=$(hyprctl monitors all | grep "DP-8")
if [[ -z "$monitor" ]]; then
	from=$to/monitors/laptop.conf
else
	from=$to/monitors/qdoled.conf
fi

name=$(basename $from)

log "use screen: $name"

copy_file $from $to "monitor.conf"

# reload everything
execute reload
