#!/usr/bin/env bash

source $HOME/.bashlib

to="$HOME/.config/hypr/monitor.conf"

monitor=$(hyprctl monitors all | grep "(ID 1)")
if [[ -z "$monitor" ]]; then
	echo "monitor=eDP-1,preferred,auto,auto" > $to
else
	id=$(echo $monitor | awk -F" " '{ print $2 }')
	echo "monitor=$id,preferred,auto,auto" > $to
	echo "monitor=eDP-1,disable" >> $to
fi

# reload everything
execute reload
