#!/usr/bin/env bash

preselected="$1"

if [[ -z "$preselected" ]]; then
	theme=$(cat $HOME/.themes | fzf)
else
	theme=$(cat $HOME/.themes | grep $preselected)
fi

if [[ -z "$theme" ]]; then
	echo "error: could not determine theme to apply - none matched your input"
	exit 1
fi

line_count=$(echo "$theme" | wc -l)
if [[ "$line_count" != "1" ]]; then
	echo "error: could not determine theme to apply: $theme"
	exit 1
fi

wp=$(echo $theme | awk -F": " '{ print $2 }')
theme=$(echo $theme | awk -F": " '{ print $1 }')

./.config/waybar/theme $theme

# TODO
# rofi
# hyprland
./.config/hypr/theme $theme

# hyprpaper
wallpaper $wp

# reload everything
reload
