#!/usr/bin/env bash

source $HOME/.bashlib

preselected="$1"

if [[ -z "$preselected" ]]; then
	theme=$(ls $HOME/.local/themes | fzf)
else
	theme=$(ls $HOME/.local/themes | fzf -q $preselected)
fi

if [[ -z "$theme" ]]; then
	echo "error: could not determine theme to apply - none matched your input"
	exit 1
fi

line_count=$(echo "$theme" | wc -l)
if [[ "$line_count" != "1" ]]; then
	echo "error: could not determine theme to apply: $theme"
	exit 1
fi

dir="$HOME/.local/themes/$theme"
fallback="$HOME/.local/themes/_fallback"

# NOTE: waybar
if [[ -f "$dir/waybar.css" ]]; then
	copy_file "$dir/waybar.css" "$HOME/.config/waybar" "theme.css"
else
	copy_file "$fallback/waybar.css" "$HOME/.config/waybar" "theme.css"
fi

# NOTE: ghostty
if [[ -f "$dir/ghostty" ]]; then
	copy_file "$dir/ghostty" "$HOME/.config/ghostty" "theme"
else
	copy_file "$fallback/ghostty" "$HOME/.config/ghostty" "theme"
fi

# NOTE: hyprland
if [[ -f "$dir/hyprland.conf" ]]; then
	copy_file "$dir/hyperland.conf" "$HOME/.config/hypr" "theme.conf"
else
	copy_file "$fallback/hyprland.conf" "$HOME/.config/hypr" "theme.conf"
fi

# TODO:
# NOTE: rofi

# TODO:
# NOTE: dunst

# TODO:
# NOTE: neovim

# TODO:
# NOTE: fzf

# NOTE: hyprpaper
wallpaper $theme
